
test:
  image: python:latest
  variables:
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  cache:
    paths:
      - .cache/pip
      - venv/
  before_script:
    - python3 -V  # Print out python version for debugging
    - pip3 install virtualenv
    - virtualenv venv
    - source venv/bin/activate
    - pip install -e ".[dev]"
  stage: test
  script:
    - python3 -m unittest
  rules:
    - if: $CI_COMMIT_BRANCH
      changes:
        compare_to: $CI_COMMIT_BRANCH
        paths:
          - 'dbcc'
          - '.gitlab/templates/.test.yml'
          - 'tox.ini'
          - 'pytest.ini'
          - 'setup.py'
          - 'pyproject.toml'
          - '.pre-commit-config.yaml'