
test:
  image: python:latest
  variables:
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  cache:
    paths:
      - .cache/pip
      - venv/
  before_script:
    - python3 -V  # Print out python version for debugging
    - pip3 install virtualenv
    - virtualenv venv
    - source venv/bin/activate
    - pip install -e ".[dev]"
  stage: test
  script:
    - python3 -m unittest
  rules:
    - changes:
        - dbcc/*
        - .gitlab/templates/.test.yml
        - tox.ini
        - pytest.ini
        - setup.py
        - pyproject.toml
        - .pre-commit-config.yaml
  tags:
    - 5.188.119.62-docker